# Generated by Django 4.0.5 on 2023-01-31 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('idPresupuesto', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de categoría')),
                ('nombreCliente', models.CharField(max_length=150, verbose_name='Nombre de la categoría')),
                ('telefonoCliente', models.IntegerField(help_text='914567845', verbose_name='Telefono Cliente')),
                ('correoCliente', models.CharField(max_length=150, verbose_name='Correo Cliente')),
                ('direccionCliente', models.CharField(max_length=300, verbose_name='Dirección')),
                ('descripcionPresupuesto', models.CharField(max_length=500, verbose_name='Descripción')),
            ],
        ),
    ]
