# Generated by Django 4.0.5 on 2023-02-09 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='idPresupuesto',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID de Presupuesto'),
        ),
    ]
